"""empty message

Revision ID: 08aa97a27b97
Revises: 76a1608f1fc3
Create Date: 2017-02-10 18:48:42.473005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08aa97a27b97'
down_revision = '76a1608f1fc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('name', sa.String(length=32), nullable=False))
    op.drop_constraint('role_role_key', 'role', type_='unique')
    op.create_unique_constraint(None, 'role', ['name'])
    op.drop_column('role', 'role')
    op.add_column('user', sa.Column('tariff_off_date', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('tariff_on_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tariff_on_date')
    op.drop_column('user', 'tariff_off_date')
    op.add_column('role', sa.Column('role', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'role', type_='unique')
    op.create_unique_constraint('role_role_key', 'role', ['role'])
    op.drop_column('role', 'name')
    # ### end Alembic commands ###
