"""empty message

Revision ID: 76a1608f1fc3
Revises: 9f3019936d00
Create Date: 2017-02-10 16:04:05.336737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a1608f1fc3'
down_revision = '9f3019936d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tariff_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_tariff_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'tariff', ['tariff_id'], ['id'])
    op.drop_column('user', 'tariff')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tariff', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_tariff_fkey', 'user', 'tariff', ['tariff'], ['id'])
    op.drop_column('user', 'tariff_id')
    # ### end Alembic commands ###
